### ISSUE TITLE
Problem running script

### ISSUE THREAD

**Issue by RiverMartinezG** [joedicastro/lftp-mirror#3]
I got the following error when running the script, I hope you can guide me, greetings.

![captura de pantalla de 2014-08-19 16 40 06](https://cloud.githubusercontent.com/assets/1312549/3974246/e0a39a8c-27f1-11e4-96a3-9ebcaa65f56f.png)

**Comment by joedicastro** [comment]
Sure, I suppose that you tried first the original `sample.cfg` file without changes and worked fine, and then failed after you edited it, right?

Well, the error that you show me happes in the `password` field, and it happens because you are inserting your password in _"plain text"_ and has to be encoded in **base64** for a minimal security (even if is testimonial).

An easy way to obtain the _base64_ coded version of you password is doing something like this in your command line:

``` sh
$ echo yourpassword | base64
eW91cnBhc3N3b3JkCg==
```

And the output ( `eW91cnBhc3N3b3JkCg==` in this case) is the string that you have to put in password's field in the `*.cfg` file.

**Comment by RiverMartinezG** [comment]
Thank you very much, indeed the error was with the password.
